fix crash SIGSEGV caused by referencing deleted iterator in iteration
Framstag/libosmscout pull request #1014
Opened 2021-03-21 11:51 UTC by janbar

Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8 in tid 28485 (qtMainLoopThrea), pid 28463
(QScopedPointer<QObjectData, QScopedPointerDeleter<QObjectData>>::operator->() const+12)
(QObject::parent() const+28)
(osmscout::LocationEntry::LocationEntry(osmscout::LocationEntry const&)+80)
(osmscout::LocationListModel::onSearchResult(QString, QList<osmscout::LocationEntry>)+1552)

Platform: Qt5.12.9, arm64

The fix erase merged locations outside of the loop

2021-03-21 15:24 UTC, Karry commented
Hi. Are you able to reproduce this crash? Can try it will full debug symbols, to see source line numbers? I don't see problem in current code. Element in the list is always erased and iterator to is overwritten... `iterator = list.erase(iterator);`

2021-03-21 15:59 UTC, janbar commented
Hi, yes I able to reproduce. The crash occurs on arm64 (Android). My app running on my pc x86_64 doesn't crash for the same search.

2021-03-21 16:29 UTC, Karry commented
As the crash is happening in `QObject::parent()` method called from `LocationEntry` copy constructor, I am worry that the issue may be somewhere else than erasing list elements... 

When you are able to reproduce it, your change fixed the issue, right? Getting full stracktrace may be tricky, "println debugging" may be faster :-) 

I am using library on x86_64 (Qt 5.12.8) and armv7 (Qt 5.6.3) without any sign of trouble, even with address sanitizer...

2021-03-21 16:36 UTC, janbar commented
Yes that's right, my change fixed the issue. I have tried to investigate on the copy constructor but nothing found. I deduced the copy was made in an container operation and a double free occurred somewhere.

2021-03-25 04:47 UTC, Framstag commented
@Karry @janbar Merge or not merge?

2021-03-25 09:32 UTC, Karry commented
I would like to know exact reason of the crash, because I don't see issue in current code. I am worry that this patch is just workaround, not a solution. I hope that I will be able to build and test code on aarch64 device soon, or @janbar will be able to dig deeper into the issue.

2021-03-25 10:04 UTC, janbar commented
@karry, seems it is not fully fixed, @Framstag succeeded to crash the search even with this patch. I retry to build the android apk to be sure this patch was applied in my branch.

2021-03-25 10:12 UTC, janbar commented
So no fixed yet. The crash occurs when searching for place "Bla". Also it crashes also with arch armv7. I have to enable the debug with symbols to understand what happens.

2021-03-25 11:31 UTC, janbar commented
After putting a lot of qWarning(__FUNCTION__  + __LINE), I saw the crash occurs here:
```
std::sort(foundLocations.begin(), foundLocations.end(), Compare);
```

2021-03-25 11:53 UTC, janbar commented
Inside the lambda "compare", calling `qWarning("%s: %d b = %s", __FUNCTION__, __LINE__, b.getLabel().toUtf8().constData());` , it crashes with SIGSEGV, SIGV_MAPERR on b.getLabel() + QString(QString)
:
```
03-25 12:46:07.489  9113  9138 W osmin   : operator(): 185 comparaisonCall = 569
03-25 12:46:07.489  9113  9138 W osmin   : operator(): 187 compareFN return OK
03-25 12:46:07.489  9113  9138 W osmin   : operator(): 179 a = Gleisdreieck e.V.
03-25 12:46:07.489  9113  9138 W osmin   : operator(): 180 b = Gleisdreieck e.V.
03-25 12:46:07.489  9113  9138 W osmin   : operator(): 185 comparaisonCall = 570
03-25 12:46:07.489  9113  9138 W osmin   : operator(): 187 compareFN return OK
03-25 12:46:07.489  9113  9138 W osmin   : operator(): 179 a = Gleisdreieck e.V.
03-25 12:46:07.489  9113  9138 W osmin   : operator(): 180 b = Gleisdreieck e.V.
03-25 12:46:07.489  9113  9138 W osmin   : operator(): 185 comparaisonCall = 571
03-25 12:46:07.489  9113  9138 W osmin   : operator(): 187 compareFN return OK
03-25 12:46:07.489  9113  9138 W osmin   : operator(): 179 a = Gleisdreieck e.V.
03-25 12:46:07.494  9113  9138 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x18 in tid 9138 (qtMainLoopThrea), pid 9113 (ub.janbar.osmin)
03-25 12:46:07.657  9188  9188 F DEBUG   : pid: 9113, tid: 9138, name: qtMainLoopThrea  >>> io.github.janbar.osmin <<<
03-25 12:46:07.671  9188  9188 F DEBUG   :     #00 pc 00000000003e42fc  /data/app/io.github.janbar.osmin-Q81UK4nYiDHvh_6hCYoEvQ==/lib/arm64/libosmin.so (QString::QString(QString const&)+48)
03-25 12:46:07.671  9188  9188 F DEBUG   :     #01 pc 00000000004f681c  /data/app/io.github.janbar.osmin-Q81UK4nYiDHvh_6hCYoEvQ==/lib/arm64/libosmin.so (osmscout::LocationEntry::getLabel() const+32)
03-25 12:46:07.671  9188  9188 F DEBUG   :     #02 pc 0000000000530004  /data/app/io.github.janbar.osmin-Q81UK4nYiDHvh_6hCYoEvQ==/lib/arm64/libosmin.so (_ZZN8osmscout17LocationListModel14onSearchResultE7QString5QListINS_13LocationEntryEEENK3$_1clERS3_RKS3_+108)
```

2021-03-25 12:25 UTC, janbar commented
I guess the issue is in the QML engine itself. I don't know how are handle compareFn and equalsFn , who is set these pointer and when ... ???

2021-03-25 12:46 UTC, janbar commented
@karry, unassigning compare() and equals() from the LocationListModel in QML code then the issue doesn't occurs anymore. Those JS function are inspired from your original code in OSMScout. I have to investigate what happens here with Qt >= 5.12 ...

2021-03-25 14:45 UTC, janbar commented
@Karry, I found !!!

2021-03-25 15:46 UTC, janbar commented
The root cause seems to be a mix with iterator and iterator of pointer. A sample as follow:
https://github.com/Framstag/libosmscout/blob/fcc882e32347c7c77e07ba30080a060a984eae80/libosmscout-client-qt/src/osmscout/SearchLocationModel.cpp#L197
But fixing this one is not enought. Finally I changed the container foundLocations to store new allocated pointer instead copying entry from the const list. Then I free (delete) merged entries and all they aren't inserted into the list of the model.

2021-03-25 17:13 UTC, Karry commented
You are right. Problem is in iterator to pointer! `LocationEntry` constructors (with `QObject* parent = nullptr`) should be explicit, compiler then shows where the problem is. Current code works, because pointer to location entry is used as a parent (implicit constructor). 

And problem starts. When entry copy is tranferred to the QML, its ownership is setup (QML don't takes ownership in that case), when parent is deleted from c++ code, Qt is deleting even children that may be referenced from QML that time... and it crash!

To correct it
 - problematic `LocationEntry` constructor have to be explicit
 - iterator have to be de-referenced twice 
 - we should add `assert(a.parent() == nullptr && b.parent() == nullptr);` to `Compare` function

Thank you @janbar !

2021-03-25 18:49 UTC, Framstag commented
@Karry Waiting for your approval
@janbar Please offer I new osmin download afterwards, so I can test https://github.com/janbar/osmin/issues/1 and routing, too :-)

2021-03-25 18:49 UTC, janbar commented
The current commit works perfectly. I tested many search and the crash no longer occurs.

Now I try to make only the change you mentioned ... and it crash again ;-).

Rolbacking to this commit and no longer crash.

2021-03-25 18:50 UTC, janbar commented
@framstag, sure , a couple of minutes ...

2021-03-25 18:57 UTC, Framstag commented
> @Framstag, sure , a couple of minutes ...

I already got a release message, however there are only source assets available? Should I wait?

2021-03-25 19:01 UTC, janbar commented
@Framstag , yes you should, the apk are uploading ....

2021-03-25 19:04 UTC, janbar commented
@Framstag , the apk are available now.

2021-03-25 19:13 UTC, janbar commented
Using pointers for QObject in functor (lambda) seems to resolve the issue. But I don't know why ...

2021-03-26 08:10 UTC, Karry commented
I would like to offer more simpler fix: https://github.com/Framstag/libosmscout/pull/1024
Problem is described there. Thank you @janbar for investigation.

2021-03-29 06:09 UTC, Karry commented
I tried to reproduce this crash on my raspberry (armv7) with llvm libc++, but unsuccessfully. I would really love to know where the problem is, but I am giving up for now. You are right that QList copies share underlying data that are copied on modification, it may be tricky on arm memory model... When some simplification in code solve the issue, I am ok with it. We waste many hours on it right now, there are more interesting things to do.

I would like to ask you for last modification - please use `std::shared_ptr` on places with `LocationEntry` - even slot/signal api, raw pointers are painful for usage. Just create some new type like `using LocationEntryPtr = std::shared_ptr<LocationEntry>`...

2021-03-29 09:52 UTC, janbar commented
@Karry, right I will make those update using shared pointers.

2021-03-29 11:22 UTC, janbar commented
@karry,
Using shared pointer is not feasible because the ownership cannot be transferred when we push entry to the model list.
Even using unique pointer is feasible, but we cannot mix pointer and std::unique_ptr when calling the functor "compare". Currently the list model store pointer aka (*LocationEntry) and if you want use unique_ptr we have to create a second functor compare(std::unique_ptr& a, std::unique_ptr& b) to handle the sort on entries of the working list foundLocation.

2021-03-29 12:02 UTC, Karry commented
> Using shared pointer is not feasible because the ownership cannot be transferred when we push entry to the model list
why? :-) You may share one `shared_ptr` from multiple collections...

2021-03-29 12:44 UTC, janbar commented
> > Using shared pointer is not feasible because the ownership cannot be transferred when we push entry to the model list
> 
> why? :-) what lines do you mean? You may share one `shared_ptr` from multiple collections...

@karry, using shared pointer you cannot release the ownership when transfering the pointer into the list model:
`positionIt = locations.insert(positionIt, location)`
Using unique pointer you can:
`positionIt = locations.insert(positionIt, location.release())`
But also we need to create a specialized functor "compare" to handle the sort of the list `foundLocations<std::unique_ptr<LocationEntry> >`.

2021-03-29 13:07 UTC, janbar commented
I do it for sport ;-) ... and you will see

2021-03-29 13:23 UTC, janbar commented
Need test on arm64 and armv7 ...

2021-03-29 13:35 UTC, janbar commented
All work great on x86 and arm64. No armv7 around me but it should be same as arm64.

2021-03-29 13:35 UTC, janbar commented
I squash the commits to make only one for merging if you agree ;-)

2021-03-29 13:44 UTC, janbar commented
Please let me know if you want I change the comment in the commit to give us a better explanation of this weird issue.

2021-03-29 14:31 UTC, janbar commented
@Karry, sorry I haven't read you full message before, because I am working at the the time :-D. So understood now I can make changes everywhere is required ...

2021-03-29 14:45 UTC, janbar commented
Don't see where I can do more. We should keep pointer for QML bindings in others places.

2021-03-30 06:51 UTC, Karry requested changes
LGTM otherwise, thank you!

2021-03-30 06:51 UTC, Karry commented on libosmscout-client-qt/src/osmscout/NearPOIModel.cpp
> +    locations.insert(position, LocationEntryRef(new LocationEntry(location)));
Instead of allocating with `new` I would use:
```
locations.insert(position, std::make_shared<LocationEntry>(location));
```

2021-03-30 06:51 UTC, Karry commented on libosmscout-client-qt/src/osmscout/SearchLocationModel.cpp
> +    foundLocations.push_back(LocationEntryRef(new LocationEntry(e)));
Instead of allocating with `new` I would use:
```
foundLocations.push_back(std::make_shared<LocationEntry>(e));
```

2021-03-30 06:51 UTC, Karry commented on libosmscout-client-qt/src/osmscout/SearchLocationModel.cpp
> +      LocationEntryRef location=LocationEntryRef(new LocationEntry(label, coord));
`std::make_shared<LocationEntry>(label, coord)` please :-)

2021-03-30 06:51 UTC, Karry commented on libosmscout-client-qt/src/osmscout/NearPOIModel.cpp
> +    for (LocationEntryRef& secondLocation:locations) {
`secondLocation` may be const here, right?

2021-03-30 08:12 UTC, Karry approved these changes

2021-03-30 08:18 UTC, merged

2021-03-31 16:05 UTC, janbar commented
@karry, bad news it crashes again using shared pointer.  I investigate.....

2021-03-31 16:10 UTC, janbar commented
@Karry, bad news it crashes again with shared pointers. II iinvestigate and retry with pointers...

2021-03-31 16:20 UTC, janbar commented
@Karry , bad news it crashes again with shared pointers. I investigate and retry with pointers ...

2021-03-31 16:22 UTC, janbar commented
Once at home I retry passing primitve pointers and let you know