I would like to merge with master a set of little features
Framstag/libosmscout pull request #1015
Opened 2021-03-21 16:54 UTC by janbar

Hi, first many thanks for this project. Yesterday I consumed the day to rebase my changes with the master and I decide to propose some changes to be definitively in the master branch. You can refuse it, then I will continue to rebase. I explained the purpose of each commit, and there are really small and non intrusive.

2021-03-21 17:26 UTC, Framstag requested changes

2021-03-21 17:26 UTC, Framstag commented on libosmscout/include/osmscout/navigation/DataAgent.h
>                                   requestMessage->bbox.GetMaxCoord()) > Kilometers(2)){
I do not like a hardcoded value like this in generic code. The value should be configurable (with a sensible default).

2021-03-21 17:29 UTC, Framstag commented
@janbar Thanks for your path. Most of it looks OK, but since most changes are in qt client library it is up to @Karry :-)

Please try to offer smaller patches in future. This allows use to let all patches pass quickly that are OK, without waiting for corrections for the complete patch while only a minor fix for a small part is required to change.

2021-03-21 17:33 UTC, janbar commented
I can split the PR for each commit If you prefer.

2021-03-21 17:50 UTC, Framstag commented
If it is OK for @Karry it is OK for me with this one the way it is. This was just meant as a hint for future patches (which I'll enjoy to see of course :-)).

2021-03-21 18:20 UTC, Karry commented
Hi @janbar. Thank you for contribution! I just start reviewing changes commit by commit. Some of them is absolutely fine and we may merge them as it. But I would like to discuss other commits. For example HiDPI change in MapPainter...

I would really love to have these changes as separate merge requests.

2021-03-21 18:58 UTC, janbar commented
@Karry , Please let me know which commits must be moved to new PRs.

2021-03-21 20:09 UTC, janbar commented
Voila I splitted the initial PR.

2021-03-25 04:48 UTC, Framstag commented
We now moved much of the changes to individual patches. I assume that I reject this patch, but is there anything left not merged via other patches?

2021-03-25 09:24 UTC, janbar commented
@Framstag , still here the important commits:

- "introduce a signal to break request on no route" 
This one send a new message to the navigation module frontend : "BreakRequest" to inform it there is no route available around the limited area. If the navigation module handles this new message, it no longer try to reroute automatically and it should ask to the user to reroute on demand i.e by pressing a button.
Sending the message we don't try to calculate a new route because in many case I tested on real courses, it will crash the lib after stucking the cpu ... to find a way the browsed area is huge.

- "fix uninitialized position"
 This one fix an issue during navigation when the current position is unavailable for an instant. In this case the map move to the unintialized position (lat 0, lon 0) in the middle of atlantic ocean, then on next change of position the map move again to the valid position. So here I initialize the new position the the last valid position.

2021-03-25 10:17 UTC, Framstag commented
I suggest to make individual pacthes for these, too. Simply because I have the impression that this work good for all participians. 

I encurrange you also to use the GitHub mechanismen for marking reviewer, acking reviews for this. I'm currently the only one to merge, but do not have the time to do in deep reviews myself. Having clear status, allows to you "blindly" merge (fast).

OK for you?

2021-03-25 16:53 UTC, janbar commented
Ok. I move the commit "fix uninitialized position" in a new PR.

2021-03-26 09:07 UTC, Karry commented on libosmscout/include/osmscout/navigation/DataAgent.h
> +          return result;
When requested area is huge, it doesn't mean that there are no routable objects, right? If I understand problem correctly, main issue is in `PositionAgent` that is requesting data again and again and cause infinite loop that leads to stack overflow, right? Would not be better to fix issue in `PositionAgent` itself instead of moving responsibility to UI code or worse - user, to re-try whole routing?

2021-03-26 09:09 UTC, Karry commented
Btw @janbar, do you have some recorded gpx track where this problem happened? It should be possible to reproduce it in `NavigationSimulation` demo...

2021-03-26 09:11 UTC, Karry commented
> Ok. I move the commit "fix uninitialized position" in a new PR.

Thank you. This commit is simple and straightforward.

2021-03-26 10:12 UTC, janbar commented
> Btw @janbar, do you have some recorded gpx track where this problem happened? It should be possible to reproduce it in `NavigationSimulation` demo...

I haven't track record to check it. But it is simple to reproduce:
- Make a route from your position to a place
- Launch the routing
- Start to follow the route for i.e 1 km
- Finally take an other way in the land (a non-drivable path): after few meters (100 or more) the router recalculate a new route ... but in this case it cannot find it ... I let you see what happens ...

2021-03-28 09:09 UTC, Karry commented
Hi, I tried simulation with "car" vehicle and use record from [our hike](https://osmscout.karry.cz/tests/Lecice.gpx) to simulate gpx. When position leave planned route, position state switched to OffRoute state, route was re-planned... When position goes to the track (not routable for a car), re-routing fails, route state switched to Unitialized and nothing special happened then. So I am not able to reproduce your issue. At least with NavigationSimulation demo :-/

2021-03-28 17:24 UTC, janbar commented
@Karry, the next week I will try the app without this patch and with the latest libosmscout. May be some changes since last months have fixed this issue.

2021-03-28 18:27 UTC, janbar commented
@Karry, running a simulation with the app and latest libosmscout the issue does not occur on my desktop. No high cpu usage like before when the position is in the land. So like you. I will confirm during the week by a real test on road / off road.
Great news if it has been resolved !

2021-03-29 07:47 UTC, Karry commented
It sounds promising! Btw, I may recommend you to start tracker when you are using navigation. It is not fun to do debugging while you are driving :-D I found this simulator very useful...

2021-04-02 14:13 UTC, janbar commented
I will give a response this week-end if the issue has been resolved. Until now I have no longer the issue with the latest master.

2021-04-04 20:31 UTC, janbar commented on libosmscout/include/osmscout/navigation/DataAgent.h
> +          return result;
Yes you are right. Please see my next comments.

2021-04-04 20:50 UTC, janbar commented
The initial issue no longer exits when you move in an area without possible route. Still one case where a similar issue come back (high cpu usage by the navigation module). It is tricky but you can reproduce easilly as follows:

- disconnect the gps sensor: so the position is invalid (i.e lat=0 , lon=0, posValid=false)
- make a route from a location you choose on the map, to an other location as destination.
- start navigation by setup navigation module with the calculated route, and the destination.

A similar issue occurs.

I am able to reproduce this case on a PC without positionning module. Or setuping the navigation module when sensor become disconnected.

2021-04-06 05:19 UTC, Framstag commented
Sounds like you should make an issue with a simple reproducer for the issue you mentioned. If you do not need this pull request anymore, please delete it.

Many thanks for the various improvements that were initially part of this request!

2021-04-06 07:26 UTC, janbar commented
I will create an issue about the last test case

2021-04-06 07:26 UTC, closed without merging