Add a demo map viewer for QtWidgets
Framstag/libosmscout pull request #1483
Opened 2023-08-10 14:15 UTC by syyyr

In our app, we only need a simple map viewer that doesn't use QML. It seems to me that a QtWidgets demo app was missing from _libosmscout_, so I made one.

This map viewer is very simple. It shows it in a window and supports moving the map with the mouse cursor and zooming with the mouse wheel.

2023-08-10 14:39 UTC, syyyr commented
It seems that CI compiles the project with Qt 5.12. Is this version still supported by libosmscout? Should I port my PR to that version?

2023-08-12 06:01 UTC, Framstag commented
@Karry What is your opinion?

2023-08-12 22:02 UTC, Karry requested changes
Hi. I like it in general :-) 

In client-qt library, I am keeping compatibility with Qt 5.6, because of slow progress in Sailfish OS. But we don't have to keep it in all demos. In other hand, test the build on Ubuntu 20.04 is beneficial IMHO. So, you may add check to CMake and Meson for Qt version and skip this demo with old Qt, or just add `#if QT_VERSION < 0x051400` and use `QWheelEvent::pos()` that is deprecated now... 

I do not like code that is full of macros, but there is no other option when we support range of Qt versions with evolving api.

2023-08-14 09:05 UTC, syyyr commented on Demos/CMakeLists.txt
> +	osmscout_demo_project(NAME QtWidgetsDemoApp SOURCES src/QtWidgetsDemoApp.cpp TARGET OSMScout::ClientQt)
Done

2023-08-14 09:05 UTC, syyyr commented
I moved the CMake declaration and added an ifdef for pos(). Hopefully it'll build now.

2023-08-14 16:02 UTC, Framstag approved these changes
Looks OK for me.

2023-08-17 09:57 UTC, Karry approved these changes

2023-08-17 18:01 UTC, merged