Bugfixes
Framstag/libosmscout pull request #924
Opened 2020-09-28 08:26 UTC by OgreTransporter

**Fix missing headers for std::string_view (issue #923)**
The GCC and CLANG forgive much easier if you forget headers from the standard library. MSVC is very strict about this. Header `<string_view>` is required to compile with VS2017 (https://en.cppreference.com/w/cpp/string/basic_string_view/operator%22%22sv).

**Resolve 2/3 Qt deprecation warnings (issue #879)**
Somewhere we already had the discussion about the QT version. As far as I'm concerned, you can assume 5.14, but on some old systems there is only QT 5.6 for licensing reasons, so the old code is still included. I could not (yet) find the problem `bool QVariant::operator>(const QVariant&) const`.

2020-09-28 16:43 UTC, Framstag commented
Regarding the meson based builds. The tests that (up to know) did not need catch.hh did not add "testIncDir" as include dir. In the meson build ou have to change for them

```
             include_directories: [osmscoutIncDir],
```

to

```
             include_directories: [testIncDir, osmscoutIncDir],
```

2020-09-28 17:19 UTC, Karry requested changes
After fast review, it looks good. But Meson - based build is broken. Make sure that you add `testIncDir` (with catch.hpp) to all tests that are using Catch...

2020-09-29 11:16 UTC, OgreTransporter commented
Sorry, I did not think of meason. With CMake you should find the right directory everywhere in it. I will correct this later.

2020-10-02 18:04 UTC, Karry approved these changes
LGTM. Meson build is working now. But `ninja test` executes 33 tests, and `ctest` 37. So, some tests are missing in Meson build ;-) It may be solved later...

2020-10-02 18:10 UTC, merged